// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/80060c94ef549c077a011977c2b5461bd0fd8947/humps/index.d.ts
declare namespace humps {

	function camelize(value: string): string;
	function pascalize(value: string): string;
	function decamelize(value: string, optionsOrProcessor?: OptionOrProcessor): string;
	function depascalize(value: string, optionsOrProcessor?: OptionOrProcessor): string;

	function camelizeKeys(str: Object, optionsOrProcessor?: OptionOrProcessor): Object;
	function pascalizeKeys(str: Object, optionsOrProcessor?: OptionOrProcessor): Object;
	function decamelizeKeys(str: Object, optionsOrProcessor?: OptionOrProcessor): Object;
	function depascalizeKeys(str: Object, optionsOrProcessor?: OptionOrProcessor): Object;

	function camelizeKeys(str: Object[], optionsOrProcessor?: OptionOrProcessor): Object[];
	function pascalizeKeys(str: Object[], optionsOrProcessor?: OptionOrProcessor): Object[];
	function decamelizeKeys(str: Object[], optionsOrProcessor?: OptionOrProcessor): Object[];
	function depascalizeKeys(str: Object[], optionsOrProcessor?: OptionOrProcessor): Object[];

	interface HumpsOptions {
		separator?: string;
		split?: RegExp;
		process?: HumpsProcessor;
	}
	interface HumpsProcessor {
		(key: string, convert: HumpsProcessorParameter, options?: HumpsOptions): string;
	}
	interface HumpsProcessorParameter {
		(key: string, options?: HumpsOptions): string;
	}
	type OptionOrProcessor = HumpsOptions | HumpsProcessor;
}

declare module "humps" {
	export = humps;
}
