// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/337587de8c13868283993bfacdcdd1a0f3291e7f/callsite/index.d.ts
declare module 'callsite' {
// Type definitions for callsite 1.0.0
// Project: https://github.com/tj/callsite
// Definitions by: newclear <https://github.com/newclear>
// Definitions: https://github.com/newclear/DefinitelyTyped



namespace Callsite {

    interface CallSite {
        getThis(): any;
        getTypeName(): string;
        getFunctionName(): string;
        getMethodName(): string;
        getFileName(): string;
        getLineNumber(): number;
        getColumnNumber(): number;
        getFunction(): Function;
        getEvalOrigin(): string;
        isNative(): boolean;
        isToplevel(): boolean;
        isEval(): boolean;
        isConstructor(): boolean;
    }
}

function Callsite(): Callsite.CallSite[];

export = Callsite;
}
